# Generated by Django 3.2 on 2021-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdate', models.DateTimeField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('matchid', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
